import Foundation

/// The full catalog of sixty side quests, ten per arena.
enum QuestLibrary {

    static let all: [Quest] = physical + mental + financial + social + adventure + creative

    static func quests(in category: QuestCategory) -> [Quest] {
        all.filter { $0.category == category }
    }

    static func quest(id: String) -> Quest? {
        all.first { $0.id == id }
    }

    // MARK: Physical

    static let physical: [Quest] = [
        Quest(id: "run-5k", category: .physical,
              title: "Run a 5K without stopping",
              flavor: "Thirty minutes of refusing to quit. Your mind gives up long before your legs do.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "pushups-100", category: .physical,
              title: "Complete 100 push-ups in one session",
              flavor: "One session, one hundred reps. Break it into sets — but finish what you start.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "learn-swim", category: .physical,
              title: "Learn to swim properly",
              flavor: "A skill that can save your life, and one most men never truly learn.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "combat-30", category: .physical,
              title: "Try a combat sport for 30 days",
              flavor: "Thirty days of learning to stay calm while someone tries to fold you in half.",
              target: 30, unit: "sessions", difficulty: .tier3),
        Quest(id: "hike-summit", category: .physical,
              title: "Hike a mountain and reach the top",
              flavor: "Pick a peak. Earn the view.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "cold-30", category: .physical,
              title: "Cold plunge for 30 days straight",
              flavor: "Thirty mornings of choosing discomfort on purpose. It rewires you.",
              target: 30, unit: "days", difficulty: .tier3),
        Quest(id: "physical-challenge", category: .physical,
              title: "Train for and complete a physical challenge",
              flavor: "Sign up for something that scares you — a race, a ruck, a fight. Then train for it.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "fast-24", category: .physical,
              title: "Fast for 24 hours and observe your mind",
              flavor: "Skip food for a day. Watch how loud your mind gets — then watch it go quiet.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "handstand", category: .physical,
              title: "Learn to do a handstand",
              flavor: "Patience, balance, and a hundred small failures. That's the point.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "steps-90", category: .physical,
              title: "Walk 10K steps every day for 90 days",
              flavor: "Ninety days of showing up. Consistency is the rarest strength.",
              target: 90, unit: "days", difficulty: .tier3),
    ]

    // MARK: Mental

    static let mental: [Quest] = [
        Quest(id: "read-12", category: .mental,
              title: "Read 12 books in one year",
              flavor: "A book a month. Borrowed wisdom is the cheapest upgrade there is.",
              target: 12, unit: "books", difficulty: .tier3),
        Quest(id: "learn-language", category: .mental,
              title: "Learn a new language to conversational level",
              flavor: "Hold a real conversation in a language you couldn't speak a year ago.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "meditate-30", category: .mental,
              title: "Meditate for 30 days without missing one",
              flavor: "Thirty days of sitting with your own mind. The hardest easy thing you'll ever do.",
              target: 30, unit: "days", difficulty: .tier2),
        Quest(id: "journal-90", category: .mental,
              title: "Write in a journal every morning for 90 days",
              flavor: "Ninety mornings of honesty on paper. You'll meet yourself there.",
              target: 90, unit: "mornings", difficulty: .tier3),
        Quest(id: "silence-day", category: .mental,
              title: "Spend one full day completely alone in silence",
              flavor: "One full day. No input, no noise. Just you and the signal.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "no-social-7", category: .mental,
              title: "Do a full week with no social media",
              flavor: "Seven days without the feed. Notice who you are when nobody's watching.",
              target: 7, unit: "days", difficulty: .tier2),
        Quest(id: "learn-chess", category: .mental,
              title: "Learn chess and actually get good at it",
              flavor: "Learn the game. Lose a hundred times. Get good.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "study-subject", category: .mental,
              title: "Study one subject you know nothing about",
              flavor: "Pick something you know nothing about and become dangerous in it.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "write-story", category: .mental,
              title: "Write your own story from beginning to now",
              flavor: "Your life, from the beginning to this moment, in your own words.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "poems-10", category: .mental,
              title: "Memorize 10 poems or quotes that move you",
              flavor: "Ten pieces of language worth carrying for the rest of your life.",
              target: 10, unit: "pieces", difficulty: .tier2),
    ]

    // MARK: Financial

    static let financial: [Quest] = [
        Quest(id: "income-stream", category: .financial,
              title: "Build one income stream outside your job",
              flavor: "Money that arrives without your boss's permission changes everything.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "save-3mo", category: .financial,
              title: "Save 3 months of expenses before anything else",
              flavor: "Three months of expenses in the bank buys the freedom to say no.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "first-invest", category: .financial,
              title: "Invest your first real amount in something",
              flavor: "Put real money to work. Skin in the game is the only teacher.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "money-basics", category: .financial,
              title: "Learn the basics of how money actually works",
              flavor: "Interest, inflation, leverage, tax. Learn the rules of the game you're already playing.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "negotiate", category: .financial,
              title: "Negotiate your salary or rate at least once",
              flavor: "One conversation. Ask for the number that makes you uncomfortable.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "sell-handmade", category: .financial,
              title: "Sell something you created with your own hands",
              flavor: "Make something with your hands and convince a stranger it's worth paying for.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "essentials-30", category: .financial,
              title: "Go 30 days spending only on necessities",
              flavor: "Thirty days of necessities only. Find out how little you actually need.",
              target: 30, unit: "days", difficulty: .tier2),
        Quest(id: "track-expenses", category: .financial,
              title: "Track every single expense for one month",
              flavor: "A month of watching where every dollar goes. The data will shock you.",
              target: 30, unit: "days", difficulty: .tier1),
        Quest(id: "wealth-book", category: .financial,
              title: "Read one serious book about wealth building",
              flavor: "One serious book on wealth. Read it with a pen in your hand.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "written-plan", category: .financial,
              title: "Have a financial plan written down on paper",
              flavor: "A financial plan, written on paper. Vague goals stay dreams.",
              target: 1, unit: "", difficulty: .tier1),
    ]

    // MARK: Social

    static let social: [Quest] = [
        Quest(id: "stranger-convo", category: .social,
              title: "Have a real conversation with a stranger",
              flavor: "Not small talk. A real conversation with someone you've never met.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "reconnect", category: .social,
              title: "Reconnect with someone you lost touch with",
              flavor: "That person you keep thinking about? Send the message.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "tell-someone", category: .social,
              title: "Tell someone exactly how much they mean to you",
              flavor: "Tell them what they mean to you. Out loud. Unprompted.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "apologize", category: .social,
              title: "Apologize to someone you owe an apology to",
              flavor: "The apology you owe. Give it clean — no excuses attached.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "friend-field", category: .social,
              title: "Make a friend in a completely different field",
              flavor: "Make a friend whose world looks nothing like yours.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "day-parent", category: .social,
              title: "Spend a full day with your father or mother",
              flavor: "A full day, undistracted. The clock on this one is real.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "letter-shaped", category: .social,
              title: "Write a letter to someone who shaped you",
              flavor: "Write to someone who shaped you and tell them exactly how.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "mentor", category: .social,
              title: "Mentor someone younger than you",
              flavor: "Teach someone younger the things you had to learn the hard way.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "host-dinner", category: .social,
              title: "Host a dinner for people who matter to you",
              flavor: "Your table, your people, one long evening. Be the reason it happened.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "brotherhood", category: .social,
              title: "Build one genuine brotherhood with other men",
              flavor: "Build one genuine circle of men who sharpen each other.",
              target: 1, unit: "", difficulty: .tier3),
    ]

    // MARK: Adventure

    static let adventure: [Quest] = [
        Quest(id: "solo-travel", category: .adventure,
              title: "Travel somewhere completely alone",
              flavor: "Somewhere completely alone. Nobody to lean on but yourself.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "sleep-stars", category: .adventure,
              title: "Sleep under the stars at least once",
              flavor: "One night with the sky as your ceiling.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "unknown-country", category: .adventure,
              title: "Visit a country where nobody knows you",
              flavor: "A place where nobody knows your name. A total reset.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "terrifies", category: .adventure,
              title: "Try one thing that genuinely terrifies you",
              flavor: "The thing you keep saying you'll do — the one that actually scares you.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "no-destination", category: .adventure,
              title: "Drive somewhere with no destination planned",
              flavor: "Get in the car. Pick a direction. See what the day gives you.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "night-ocean", category: .adventure,
              title: "Swim in the ocean at night",
              flavor: "Dark water, open sky, full presence. You'll never forget it.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "lost-city", category: .adventure,
              title: "Get lost in a city you have never visited",
              flavor: "No maps for an afternoon. Let a strange city rearrange you.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "sunrise-summit", category: .adventure,
              title: "Watch the sunrise from a summit",
              flavor: "Start in the dark. Watch the day begin from the top.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "spontaneous-24", category: .adventure,
              title: "Take a spontaneous 24-hour trip",
              flavor: "A bag, a ticket, twenty-four hours. Decided the same day.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "no-phone-day", category: .adventure,
              title: "Navigate a full day without your phone",
              flavor: "Paper maps, strangers, instinct. One day completely off the grid.",
              target: 1, unit: "", difficulty: .tier1),
    ]

    // MARK: Creative

    static let creative: [Quest] = [
        Quest(id: "cook-10", category: .creative,
              title: "Learn to cook 10 meals from scratch",
              flavor: "Ten real meals, from raw ingredients, by your own hands.",
              target: 10, unit: "meals", difficulty: .tier2),
        Quest(id: "instrument-song", category: .creative,
              title: "Pick up one instrument and play one full song",
              flavor: "One instrument, one full song, start to finish.",
              target: 1, unit: "", difficulty: .tier3),
        Quest(id: "build-fix", category: .creative,
              title: "Build or fix something with your own hands",
              flavor: "Build or fix something real. Sawdust, solder, or grease — your choice.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "write-publicly", category: .creative,
              title: "Write something honest and share it publicly",
              flavor: "Write something honest and put your name on it, in public.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "photos-year", category: .creative,
              title: "Take photos of your life for one full year",
              flavor: "Document one year of your life, one week at a time.",
              target: 52, unit: "weeks", difficulty: .tier3),
        Quest(id: "draw-30", category: .creative,
              title: "Learn to draw — even badly — and keep going",
              flavor: "Thirty sketches. Bad is the price of admission.",
              target: 30, unit: "sketches", difficulty: .tier2),
        Quest(id: "no-audience", category: .creative,
              title: "Start a project with no audience and no goal",
              flavor: "No metrics, no followers, no point — except that it's yours. Pure play.",
              target: 1, unit: "", difficulty: .tier2),
        Quest(id: "record-listen", category: .creative,
              title: "Record yourself speaking and actually listen back",
              flavor: "Record yourself speaking. Then sit down and actually listen.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "design-something", category: .creative,
              title: "Design something from nothing, even if small",
              flavor: "A logo, a bench, a garden bed. From nothing to something.",
              target: 1, unit: "", difficulty: .tier1),
        Quest(id: "create-new", category: .creative,
              title: "Create something that did not exist before you",
              flavor: "Make one thing that did not exist before you made it.",
              target: 1, unit: "", difficulty: .tier2),
    ]
}
